spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bankingdb
    username: root
    password: Floripa2402!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        hbm2ddl:
          auto: update
server:
  port: 8081